" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

" Multiple Plug commands can be written in a single line using | separators
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" elixir
Plug 'elixir-editors/vim-elixir'

" Eye candy
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tomasr/molokai'

" Git
Plug 'tpope/vim-fugitive'

" Nice to have
Plug 'ervandew/supertab'
Plug 'kien/ctrlp.vim'
Plug 'szw/vim-ctrlspace'
Plug 'skywind3000/quickmenu.vim'
Plug 'plasticboy/vim-markdown'

" Initialize plugin system
call plug#end()

" airline
let g:airline#extensions#tabline#enabled = 1

" color 
color molokai

" Cntrl space config
set hidden

" Quick Menu

" choose a favorite key to show/hide quickmenu
noremap <silent><F12> :call quickmenu#toggle(0)<cr>

 " enable cursorline (L) and cmdline help (H)
let g:quickmenu_options = "HL"

" section 1, text starting with "#" represents a section (see the screen
" capture below)
call g:quickmenu#append('# Develop', '')
call g:quickmenu#append('test', '!mix test', 'Run all the tests')
call g:quickmenu#append('build', '!mix compile', 'Build the code')

